### ISSUE TITLE
cursor size should be set from screen DPI

### ISSUE THREAD

**Issue by danisla** [selkies-project/selkies#87]
Rather than setting a static cursor size from the `cursor_size` argument, cursor size should match the client screen DPI.

In my tests, the cursor appears very large.

It doesn't look like there is a way to disable the cursor resize accessibility feature and revert back to the standard cursor sizes, only a fixed forced resize is possible now.

In general, things like remote DPI and cursor sizes should match the client per the Javascript `window.devicePixelRatio` variable.

The remote screen DPI should also match the client DPI, but that is another issue.

**Comment by ehfd** [comment]
What about the remote cursors when Ctrl+Shift+Click is used, then? It will be much smaller than the client cursors.

**Comment by danisla** [comment]
I'm working on a PR to match the remote DPI to the local client DPI, which will scale the remote cursors too.

**Comment by ehfd** [comment]
Great.

**Comment by danisla** [comment]
Fixed with #88

**Comment by ehfd** [comment]
> Resize remote cursor to match local scaling. Requires scalable cursor theme to be used such as dmz-cursor-theme

Does this mean breeze-cursor-theme would lead to issues? @danisla

**Comment by danisla** [comment]
> > Resize remote cursor to match local scaling. Requires scalable cursor theme to be used such as dmz-cursor-theme
> 
> Does this mean breeze-cursor-theme would lead to issues? @danisla

It's also scalable and works just fine.

You can also use the "accessible" option and pass a `--cursor_size` greater than zero to use local fixed scaling, but the default is now `-1` which follows the scale of the local client. Also, the `--cursor_size` does not affect the remote cursor when in "ctrl+shift+click" mode whereas this new method does change the remote cursor.

**Comment by ehfd** [comment]
New erratic behavior arising from the merge. @danisla 

![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/cdb9ca5d-8449-4ad4-876d-599f41b69740)

![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/e52e6829-bd0a-4239-9d27-c8385e02df60)

While I have set up Selkies to be on a consistent 1920x1080 with remote resize disabled and local resize enabled, the screen is instead resized to 1432x838, which is half of the window size 2864x1676.

**Comment by danisla** [comment]
Fixed with https://github.com/selkies-project/selkies-gstreamer/commit/4d2172c89c3ca4ad83578c0da89db53d73ea54c3

**Comment by ehfd** [comment]
![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/20bc43a4-d537-4f04-8c42-bbf384c24c68)

![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/bc4a71a1-b5d0-4ef5-b6c3-5234ef380bac)

Issue persists in the newest release. WEBRTC_ENABLE_RESIZE was set to false.

**Comment by ehfd** [comment]
One more concerning aspect is the resolution being decreased by half. @danisla

The behavior when `WEBRTC_ENABLE_RESIZE` or `--enable_resize` is true should be resizing to precisely the client resolution while only increasing the DPI.

If `WEBRTC_ENABLE_RESIZE` or `--enable_resize` is false, neither the resolution or the DPI should be changed from the default, and only cursor size should be scaled.

**Comment by danisla** [comment]
The enable resize feature matches the dimensions of your browser window, not your local graphics card. The goal is to maintain a 1:1 pixel ratio with the viewport. If you enter full screen mode the resolutions should be equal.

**Comment by ehfd** [comment]
> The enable resize feature matches the dimensions of your browser window, not your local graphics card. The goal is to maintain a 1:1 pixel ratio with the viewport. If you enter full screen mode the resolutions should be equal. 

Video: H264 1432x838

Window size: 2864x1676

**Comment by danisla** [comment]
What is your resolution scaling set to? In the js console you can get this from window.devicePixelRatio

**Comment by ehfd** [comment]
Answer: 200%

Again, please let me repeat myself.
Under no circumstances should the remote resolutions decrease because of the client pixel ratio. The remote screen blurs compared to the native client resolution. Only the remote DPI is supposed to increase by the client pixel ratio.

And also, this happens when remote resize is set to disabled.

**Comment by danisla** [comment]
Give this commit a try and let me know if it's better or worse

https://github.com/selkies-project/selkies-gstreamer/commit/010b87a66ac8fa44657d2250aa411b125a1a0330

**Comment by ehfd** [comment]
I will test.

**Comment by ehfd** [comment]
> Give this commit a try and let me know if it's better or worse

I am generally happy. But I believe that the DPI scaling should start from 120 in 1920x1080 (not 96) and scale in other resolutions from there. Looks like 1920x1080 starts from 96.

![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/ad92ff96-84b3-484e-9700-e18bc064074f)

**Comment by ehfd** [comment]
> Give this commit a try and let me know if it's better or worse

I am generally happy @danisla.
The issue with resizing when it's supposed to be off is also resolved.

But separate to the previous issue, I believe that the DPI scaling is a tad too small.

On Xfce:
![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/ad92ff96-84b3-484e-9700-e18bc064074f)

**Comment by ehfd** [comment]
Also, looks like Xfce4 is the only supported DE in resize.py.

https://gist.github.com/itsfarseen/ae2a712331d6f285e4334b3e34ef2559

I assume xrandr --dpi doesn't work?

**Comment by ehfd** [comment]
![image](https://github.com/selkies-project/selkies-gstreamer/assets/8457324/a9007451-ea2c-4157-9427-1c189ffd2f93)

Looks like windows are scaled to the intended DPI, the shell behind is not.

**Comment by danisla** [comment]
HiDPI support is DE dependent and not perfect or straightforward on Linux. 
see these docs for more info. 
https://wiki.archlinux.org/title/HiDPI

The current implementation and XFCE support is only best effort right now.
